name = "mockth"
version = "1.0.0"
description = "Erlang modules mocking library for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bondiano", repo = "mockth" }

gleam = ">= 1.9.1"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 1.0.0"
meck = "1.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleeunit = ">= 1.2.0 and < 2.0.0"
